### PR TITLE
send the email in the meta member of the token

### LINKED ISSUE #198: We need some way to lookup map between orcid/email/people/profile

### PR DESCRIPTION
**Pull request by erezmus**
Closes #198

### CODE REVIEW

**Comment by Cooryd** [comment]
This could do with some unit tests

**Comment by erezmus** [comment]
> This could do with some unit tests

This will be done as part of PR #425

**Comment by diversemix** [comment]
I'm wondering if this should be the `sub` of the JWT (see https://tools.ietf.org/html/rfc7519#section-4.1 )... then again - this might be a separate issue... @erezmus  do you mind doing some research around this - am happy to take your lead.

**Comment by thewilkybarkid** [comment]
Better to not start using email addresses as an identifier. There's a [standard `email` claim](https://www.iana.org/assignments/jwt/jwt.xhtml) that you can use.

**Comment by erezmus** [comment]
Since the profile can have multiple addresses are we assuming to use the first one?

**Comment by diversemix** [comment]
ok - let's get this in and then we can modify as or when others have use of it.

/fyi @joelsummerfield

**Pull request merged**
