### PR TITLE
fix: remove browsertest job

### PR DESCRIPTION
**Pull request by Cooryd**

### CODE REVIEW

**Comment by Cooryd** [comment]
I'm unsure if this will be enough or if I should be completely removing browsertest from the flux-cluster deployment config [here](https://github.com/elifesciences/elife-flux-cluster/blob/66476374d13f00dd3f5ff3c466f4ae17d6714b81/deployments/reviewer/libero-reviewer--stg.yaml#L78) aswell.

**Comment by NuclearRedeye** [comment]
I had the same thoughts about if this was right or not, and I'm really not sure. This might be correct, or just part of the work. But looking around I spotted [this](https://github.com/libero/reviewer/blob/master/charts/libero-reviewer/values.test.all_enabled.yaml#L44) which looks to me like possibly a toggle to disable the tests. Might be that we can set a value for this in the values in the deployment charts and that might be all that is needed.
Will wait for @erkannt to advise on the best approach.

**Review by NuclearRedeye — COMMENTED** [review]
See above comment.

**Comment by erkannt** [comment]
The browsertests are part of the helm chart defined here: https://github.com/libero/reviewer/tree/master/charts/libero-reviewer

They are disabled by default, and that default isn't overridden in either of the HelmRelease manifests (stg/prod).

The browsertests are instead triggered by flagger as part of the release cycle.
https://github.com/elifesciences/elife-flux-cluster/blob/66476374d13f00dd3f5ff3c466f4ae17d6714b81/deployments/reviewer/libero-reviewer--prod--canaries.yaml#L68

As you can see in that line flagger uses helm to trigger the tests. This way the tests could be defined and configured as part of the helm chart and their image versions kept in check that way.

If you only want to disable them: remove the three `acceptance-test-of-staging` sections from the Canary manifest.

If you want to remove them all together: browsertests and their image are defined in `libero-client` repo, the job to run them is one of the templates in the chart and if you remove that you should also clean up the `values` associated with it.

**Comment by NuclearRedeye** [comment]
Ah, yes that rings a bell when we added the ` || true` to the end of each line to ignore the result.

**Pull request closed without merging**
